AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Resources:
  LineOfCreditFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: dist
      Handler: handler.handler
      Runtime: nodejs16.x
      Events:
        Api:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: ANY
      Environment:
        Variables:
          NODE_ENV: development
