AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Resources:
  LineOfCreditFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: dist
      Handler: router.router
      Runtime: nodejs16.x
      Timeout: 30
      Events:
        Api:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: ANY
      Environment:
        Variables:
          NODE_ENV: development
          DATABASE_URL: postgresql://localhost:5432/line_of_credit
